### PR TITLE
test: run test with undici function

### PR DESCRIPTION
**Pull request by wkillerud**
Debugging an unexpectedly long timeout we saw. It seems our abortController might not reject as we expect?

### CODE REVIEW

**Comment by wkillerud** [comment]
I can't for the life of me figure out why the tests are failing in `integration.basic.test.js`. Too late on a friday.

**Comment by digitalsadhu** [comment]
We moved away from .timeout here https://github.com/podium-lib/client/pull/412

**Comment by digitalsadhu** [comment]
Worth noting that we aren't super far away from totally replacing the current implementation with the new http client

**Comment by wkillerud** [comment]
We still see a similar problem with the current implementation using `AbortController` (Error propagating instead of a promise rejection).

**Comment by wkillerud** [comment]
> Worth noting that we aren't super far away from totally replacing the current implementation with the new http client.

Maybe the fix is to replace the client then.

We should make sure to test the client against a running server though, not mock the implementation.

**Comment by digitalsadhu** [comment]
> > Worth noting that we aren't super far away from totally replacing the current implementation with the new http client.
> 
> Maybe the fix is to replace the client then.
> 
> We should make sure to test the client against a running server though, not mock the implementation.

it might not actually fix anything though seeing as its still undici based...

**Comment by digitalsadhu** [comment]
> We still see a similar problem with the current implementation using `AbortController` (Error propagating instead of a promise rejection).
> 
> Maybe we need to change how we handle timeouts all the way up to `client.fetch`

hmm odd. Vegard claimed the issue was resolved with the change. He seemed quite certain of it. What did we miss?

**Pull request closed without merging**
